import type { DimensionId, Question } from "./types";

export const dimensionLabels: Record<DimensionId, string> = {
  market: "市场竞争力",
  strategy: "战略与 KPI",
  finance: "财务现金流",
  operations: "运营效率",
  organization: "组织人才",
  growth: "增长质量",
  future: "未来计划",
};

export const questions: Question[] = [
  {
    id: 1,
    dimension: "market",
    kind: "text",
    title: "请给出您公司所在的产业类别，贵公司占 80% 销售收入的产品是什么？",
    help: "自由填写，用于后续行业和产品定位对比。",
    conclusion: "便于后续对比",
    required: true,
  },
  {
    id: 2,
    dimension: "market",
    kind: "score",
    title: "对于同行的竞争对手，主要的护城河是什么？",
    help: "0-5 分表示竞争对手可能在一年内形成重要威胁；6-8 分表示有一定障碍但两年内可能形成竞争；9-10 分表示接近垄断。",
    conclusion: "0-5 分竞争力弱，超过 6 分竞争力强",
    required: true,
    threshold: { type: "score", highBelow: 6 },
  },
  {
    id: 3,
    dimension: "market",
    kind: "score",
    title: "在您的工业领域，怎样来确定您的竞争力？",
    help: "9-10 分代表占市场顶部 25% 的竞争力且订单转化率大于 70%；6-8 分代表有一定市场竞争力；0-5 分代表碎片化市场且订单转化率低。",
    conclusion: "如果问题 2 和问题 3 都得 6 分以上，基本判断市场竞争力强",
    required: true,
    threshold: { type: "score", highBelow: 6 },
  },
  {
    id: 4,
    dimension: "market",
    kind: "score",
    title: "客户如何评价你们的独特价值？",
    help: "9-10 分代表企业闻名并制定工业标准；6-8 分代表被行业广泛认可；0-5 分代表订单严重依赖市场和销售活动。",
    conclusion: "客户认可价值在 6 分以上可认定为著名企业，在行业有话语权",
    required: true,
    threshold: { type: "score", highBelow: 6 },
  },
  {
    id: 5,
    dimension: "growth",
    kind: "score",
    title: "比较贵司综合年销售增长率在行业中的地位？",
    help: "8-10 分高于平均值；6-7 分和行业水平相同；0-5 分低于行业水平。",
    threshold: { type: "score", highBelow: 6 },
  },
  {
    id: 6,
    dimension: "finance",
    kind: "score",
    title: "你们企业挣钱吗？运营产生正现金流？",
    help: "8-10 分盈利并产生运营净现金流；6-7 分盈利但不产生正净现金流；0-5 分亏损。",
    conclusion: "5 分以下的企业为亏损企业，需要进行改善和精益指导",
    required: true,
    threshold: { type: "score", highBelow: 5, mediumBelow: 8 },
  },
  {
    id: 7,
    dimension: "strategy",
    kind: "score",
    title: "企业战略如何？",
    help: "8-10 分有书面正规战略并层层解码；6-7 分有战略但未层层落实；0-5 分战略没有被团队了解，缺少书面化和战略解码。",
    conclusion: "5 分以下，企业战略不清晰是企业失败的重要原因之一，需要进行战略咨询",
    required: true,
    threshold: { type: "score", highBelow: 6, mediumBelow: 8 },
  },
  {
    id: 8,
    dimension: "strategy",
    kind: "score",
    title: "公司有明确的 KPI 或 OKR 吗？这些指标和公司战略紧密结合吗？",
    help: "9-10 分 KPI/OKR 清晰且每周讨论；7-8 分 KPI 影响团队行为；5-6 分团队知道但未指导行为；0-4 分团队不知道 KPI。",
    conclusion: "4 分以下的企业基本不可能是规范管理企业，需要进行 KPI 落地咨询",
    required: true,
    threshold: { type: "score", highBelow: 5, mediumBelow: 8 },
  },
  {
    id: 9,
    dimension: "strategy",
    kind: "score",
    title: "公司有季度复盘吗？如何给你的企业打分？",
    help: "8-10 分每季度使用 KISS 方法复盘并形成行动计划；6-7 分每月运营会议讨论结果；0-5 分没有正式运营会议。",
    conclusion: "5 分以下企业被认为管理需要提高，需要进行复盘咨询",
    required: true,
    threshold: { type: "score", highBelow: 6, mediumBelow: 8 },
  },
  {
    id: 10,
    dimension: "organization",
    kind: "score",
    title: "高层有没有对下层员工的职业发展规划，或者采取行动使团队发挥最大效能？",
    help: "9-10 分员工知道强弱项且有发展计划；6-8 分团队知道上级看法且有书面计划；0-5 分没有书面计划。",
    conclusion: "5 分以下的企业中层管理层不稳定",
    threshold: { type: "score", highBelow: 6 },
  },
  {
    id: 11,
    dimension: "strategy",
    kind: "score",
    title: "KPI 是否可测量，并和公司具体目标挂钩？",
    help: "8-10 分每个人都知道今年三大目标，KPI 具体到日常管理；5-7 分部分实施；0-4 分基本没有。",
    conclusion: "7 分以下企业都有空间提升 KPI 的落地执行",
    threshold: { type: "score", highBelow: 5, mediumBelow: 8 },
  },
  {
    id: 12,
    dimension: "finance",
    kind: "score",
    title: "你们公司每月按时关账，获得趋势分析报告，并且有详尽的财务分析吗？",
    help: "9-10 分财务团队强且数据可靠；7-8 分有财务报告但分析不深；4-6 分报表不准或不及时；0-3 分不能按时关账。",
    conclusion: "6 分以下的公司财务管理差，需要改善",
    threshold: { type: "score", highBelow: 6, mediumBelow: 8 },
  },
  {
    id: 13,
    dimension: "finance",
    kind: "number",
    title: "毛利率是衡量企业的重要指标，你们的毛利率如何？",
    help: "请输入毛利率百分比。Excel 规则：9-10 大于 46%，8 为 31%-45%，6-7 为 21%-30%，4-5 为 11%-20%，0-3 为 0-10%。",
    conclusion: "3 分以下为不合格，需要改善毛利率，实施精益管理",
    threshold: { type: "lessThanHigh", value: 11 },
  },
  {
    id: 14,
    dimension: "finance",
    kind: "number",
    title: "过去 12 个月平均水平，你们公司产生自由现金流吗（FCF）？",
    help: "自由现金流定义为运营活动产生的现金流减去资本投资支出。请输入 FCF 金额。",
    conclusion: "3 分以下企业现金流出现问题，需要限制投资，或者增加毛利，或者增加销售收入",
    threshold: { type: "negativeIsHigh" },
  },
  {
    id: 15,
    dimension: "operations",
    kind: "score",
    title: "销售团队可以独立自主地获得订单并按时完成交货吗？",
    help: "7-10 分销售获得足够订单且运营协作良好；4-6 分获得一定订单且大部分可交货；0-3 分销售和运营配合不好。",
    conclusion: "3 分以下需要采取行动，生产计划和销售计划脱节，内部管理层次太多，生产效率低下",
    threshold: { type: "score", highBelow: 4, mediumBelow: 7 },
  },
  {
    id: 16,
    dimension: "organization",
    kind: "score",
    title: "企业有没有人才后备计划？",
    help: "9-10 分关键岗位都有后备计划；5-8 分有正式人才后备计划；0-4 分没有计划。",
    conclusion: "4 分以下企业对于关键岗位没有备选人才，会出现人才断层和运营中断风险",
    threshold: { type: "score", highBelow: 5, mediumBelow: 9 },
  },
  {
    id: 17,
    dimension: "organization",
    kind: "score",
    title: "您的员工如何评价您的交流能力、远景目标和价值观沟通？",
    help: "9-10 分远景目标价值观清晰并用于高管考核；7-8 分清晰但缺乏一贯性；4-6 分不清晰；0-4 分什么也没有。",
    conclusion: "6 分以下企业没有清晰企业远景目标价值观，需要进行改善",
    threshold: { type: "score", highBelow: 6, mediumBelow: 8 },
  },
  {
    id: 18,
    dimension: "growth",
    kind: "choice",
    title: "贵公司过去三年复合年增长率是多少？",
    help: "请选择增长区间。",
    options: ["大于 40%", "20%-30%", "小于 20%"],
    conclusion: "小于 20% 说明三个问题：产品进入成熟期、竞争力下降、市场营销乏力",
    threshold: { type: "needsIndustryBenchmark" },
  },
  {
    id: 19,
    dimension: "growth",
    kind: "number",
    title: "贵公司滚动 12 个月营收相比去年增加或减少比例？",
    help: "请输入增长率百分比，减少请输入负数。",
    conclusion: "如果减少超过 10% 说明企业增长乏力或者有什么突发情况，需要调研",
    threshold: { type: "lessThanHigh", value: -10 },
  },
  {
    id: 20,
    dimension: "finance",
    kind: "number",
    title: "贵公司滚动 12 个月毛利相比去年增加或减少比例？",
    help: "请输入毛利变化率百分比，减少请输入负数。",
    conclusion: "毛利如果出现减少，需要看看产品的结构或者固定成本",
    threshold: { type: "lessThanHigh", value: 0 },
  },
  {
    id: 21,
    dimension: "finance",
    kind: "number",
    title: "贵公司滚动 12 个月净利润相比去年增加或减少比例？",
    help: "请输入净利润变化率百分比，减少请输入负数。",
    conclusion: "净利代表企业盈利能力和现金流增加能力",
    threshold: { type: "lessThanHigh", value: 0 },
  },
  {
    id: 22,
    dimension: "finance",
    kind: "number",
    title: "贵公司滚动 12 个月资本投入相比去年增加或减少比例？",
    help: "请输入资本投入变化率百分比。",
    conclusion: "资本投入需要看项目是否有发展前景，或者产能扩展是否有销售增加来支撑",
    threshold: { type: "needsIndustryBenchmark" },
  },
  {
    id: 23,
    dimension: "finance",
    kind: "number",
    title: "贵公司可以获得的总资本是多少？",
    help: "总资本 = 贷款增加 - 每月总支出 + 净现金流。请输入金额。",
    conclusion: "出现负数或者贷款金额过大就亮红灯",
    threshold: { type: "negativeIsHigh" },
  },
  {
    id: 24,
    dimension: "finance",
    kind: "number",
    title: "过去 12 个月平均净现金流是多少？",
    help: "请输入平均净现金流金额。",
    conclusion: "出现负数亮红灯，企业现金短缺，需要减少支出",
    threshold: { type: "negativeIsHigh" },
  },
  {
    id: 25,
    dimension: "finance",
    kind: "number",
    title: "贵公司应收账款占销售收入的比例是多少？",
    help: "请输入百分比。Excel 规则：大于 100%、大于 50%、小于 50%。",
    conclusion: "大于 100% 说明滞销可能，风险增加",
    threshold: { type: "greaterThanHigh", value: 100 },
  },
  {
    id: 26,
    dimension: "operations",
    kind: "number",
    title: "贵公司存货周转次数是多少？",
    help: "和同行业平均数据对比：8-10 分大于 6 次；6-8 分 4-6 次；0-6 分小于 4 次。",
    conclusion: "小于 4 次企业可能面临现金短缺、利润下降风险、存货坏账",
    threshold: { type: "lessThanMedium", high: 4, medium: 6 },
  },
  {
    id: 27,
    dimension: "operations",
    kind: "number",
    title: "人均产值是多少？",
    help: "请输入万元/人。该指标需要和同行业数据对比。",
    conclusion: "低于 20 万/人说明机构臃肿，减人机会至少 20%",
    threshold: { type: "lessThanHigh", value: 20 },
  },
  {
    id: 28,
    dimension: "operations",
    kind: "number",
    title: "产能利用率是多少？",
    help: "请输入实际产能利用率百分比。",
    conclusion: "利用率低于 50% 说明产能严重浪费，需要进行整合",
    threshold: { type: "lessThanHigh", value: 50 },
  },
  {
    id: 29,
    dimension: "operations",
    kind: "number",
    title: "固定成本占销售额比例是多少？",
    help: "请输入百分比，该指标需要与同行业数据对比。",
    conclusion: "大于 40% 说明人浮于事",
    threshold: { type: "greaterThanHigh", value: 40 },
  },
  {
    id: 30,
    dimension: "operations",
    kind: "number",
    title: "ERP 和 MES 管理系统实施情况？",
    help: "请输入实施覆盖百分比。",
    conclusion: "低于 50% 说明数据准确性有问题，生产计划管理会很差，经常出现断货",
    threshold: { type: "lessThanHigh", value: 50 },
  },
  {
    id: 31,
    dimension: "operations",
    kind: "number",
    title: "公司整体产品质量合格率是多少，和行业对比什么水平？",
    help: "请输入质量合格率百分比。该题需要结合行业资料复核。",
    conclusion: "质量合格率低说明精益生产管理水平低下",
    threshold: { type: "needsIndustryBenchmark" },
  },
  {
    id: 32,
    dimension: "operations",
    kind: "choice",
    title: "公司有质量过程控制体系吗？SPC 控制或者其他防呆措施？",
    help: "请选择质量过程控制覆盖情况。",
    options: ["有", "部分有", "没有"],
    conclusion: "没有代表质量可靠性差，完全靠人为点检或者全检，有非常大改善空间",
  },
  {
    id: 33,
    dimension: "operations",
    kind: "score",
    title: "公司有没有精益管理组织？每天是否有精益活动？",
    help: "8-10 分有组织且每天或每周活动；6-8 分有组织每月活动；4-6 分无组织偶尔活动或培训；0-4 分无组织无培训无活动。",
    conclusion: "4 分以下有非常多的机会，质量不稳定，批量退货，不能按时交货",
    threshold: { type: "score", highBelow: 4, mediumBelow: 7 },
  },
  {
    id: 34,
    dimension: "operations",
    kind: "number",
    title: "公司有几级审批？OA 系统完整审批流程几天？",
    help: "请输入审批层级。超过 3 级审批为流程臃肿；OA 审批流超过 24 小时说明流程不畅通。",
    conclusion: "超过 3 级审批为流程臃肿，OA 审批流超过 24 小时，说明流程不畅通",
    threshold: { type: "approvalFlow" },
  },
  {
    id: 35,
    dimension: "future",
    kind: "choice",
    title: "公司未来 5 年打算？",
    help: "通过这个信息了解公司未来打算。",
    options: ["上市", "出售", "稳定生存", "存活"],
    conclusion: "通过这个信息可以了解公司未来打算",
  },
  {
    id: 36,
    dimension: "future",
    kind: "text",
    title: "公司 AI 计划，目前使用 AI 状况？",
    help: "如实填写当前 AI 使用场景、工具、团队准备和下一步计划。",
  },
  {
    id: 37,
    dimension: "future",
    kind: "choice",
    title: "公司聘请外部顾问计划？",
    help: "请选择是否有外部顾问计划。",
    options: ["有", "没有"],
  },
  {
    id: 38,
    dimension: "organization",
    kind: "text",
    title: "公司之前有没有大规模系统培训？",
    help: "如实填写培训主题、对象、周期和效果。",
  },
];

export const diagnosisSteps = [
  { id: "profile", label: "公司画像", questionIds: [1] },
  { id: "market", label: "市场竞争力", questionIds: [2, 3, 4, 5] },
  { id: "strategy", label: "战略与 KPI", questionIds: [7, 8, 9, 11] },
  { id: "finance", label: "财务现金流", questionIds: [6, 12, 13, 14, 19, 20, 21, 22, 23, 24, 25] },
  { id: "operations", label: "运营效率", questionIds: [15, 26, 27, 28, 29, 30, 31, 32, 33, 34] },
  { id: "organization", label: "组织人才", questionIds: [10, 16, 17, 38] },
  { id: "future", label: "未来计划", questionIds: [18, 35, 36, 37] },
];
